site_name: "YAOZARRS ‼️"
site_description: "Yet another ome-zarr model."
site_url: "https://tlambert03.github.io/yaozarrs/"
repo_url: "https://github.com/tlambert03/yaozarrs"
repo_name: "tlambert03/yaozarrs"

# https://zensical.org/docs/customization/
theme:
  name: material
  features:
    # - "announce.dismiss"
    - "content.code.annotate"
    - "content.code.copy"
    - "content.code.select"
    - "content.footnote.tooltips"
    - "content.tabs.link"
    - "content.tooltips"
    - "navigation.footer"
    - "navigation.indexes"
    - "navigation.instant"
    - "navigation.instant.prefetch"

  palette:
    - scheme: "default"
      primary: black
      toggle:
        icon: material/brightness-7
        name: "Switch to dark mode"
    - scheme: "slate"
      primary: black
      toggle:
        icon: material/brightness-4
        name: "Switch to light mode"

  font:
    text: "Inter"
    # code: "Fira Code"

markdown_extensions:
  toc:
    permalink: "#"
    permalink_title: "Link to this section"
  pymdownx.tabbed:
    alternate_style: true
  admonition: {}
  attr_list: {}
  md_in_html: {}
  pymdownx.details: {}
  pymdownx.superfences: {}
  pymdownx.highlight:
    pygments_lang_class: true
  pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - "https://docs.python.org/3/objects.inv"
          paths:
            - "src"
          options:
            docstring_style: "numpy"
            # inherited_members: true
            # parameter_headings: true
            # separate_signature: true
            # show_signature_annotations: true
            show_bases: false
            show_symbol_type_toc: true
            show_symbol_type_heading: true
            # good for modules
            # show_root_heading: true
            # good for hidden submodules
            heading_level: 3
            show_root_heading: false
            show_root_toc_entry: false
            members_order: "__all__"
            extensions:
              - griffe_fieldz:
                  strip_annotated: true

extra_css:
  - stylesheets/extra.css